export const languages = {
    Bash: 'sh',
    C: 'c',
    'C#': 'cs',
    'C++': 'cpp',
    CSS: 'css',
    Dart: 'dart',
    Go: 'go',
    HTML: 'html',
    Haskell: 'hs',
    Java: 'jsp',
    JavaScript: 'js',
    Julia: 'jl',
    Kotlin: 'kt',
    'Objective-C': 'm',
    PHP: 'php',
    Perl: 'pl',
    Python: 'py',
    R: 'r',
    Ruby: 'rb',
    Rust: 'rs',
    SQL: 'sql',
    Scala: 'scala',
    Swift: 'swift',
    TypeScript: 'ts',
}